- hosts: all
  become: true
  gather_facts: false
  vars:
    repo: '{{ playbook_dir | dirname | dirname }}'
    ansible_pipelining: true
  handlers:
    - name: reload sshd after password auth disabled
      listen: sshd
      command: systemctl reload sshd
      failed_when: false
  tasks:
    - name: copy containers to ishak homedir
      become_user: ishak
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dst }}'
      loop:
        - src: '{{ repo }}/llama/quadlet/'
          dst: /home/ishak/.config/containers/systemd/llama/
        - src: '{{ repo }}/llama/config/searxng.yml'
          dst: /home/ishak/.var/app/io.github.gmankab.ishak/config/searxng.yml
    - name: start systemd services
      become_user: ishak
      systemd_service:
        scope: user
        daemon_reload: true
        name: llama-pod.service
        state: restarted
